#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pymongo
Version  : 3.9.0
Release  : 42
URL      : https://files.pythonhosted.org/packages/c0/69/9388b715d013444ae8e5d497a6825d120f6a7a67ef5aa8ddea62f601cbff/pymongo-3.9.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/c0/69/9388b715d013444ae8e5d497a6825d120f6a7a67ef5aa8ddea62f601cbff/pymongo-3.9.0.tar.gz
Summary  : Python driver for MongoDB <http://www.mongodb.org>
Group    : Development/Tools
License  : Apache-2.0
Requires: pymongo-license = %{version}-%{release}
Requires: pymongo-python = %{version}-%{release}
Requires: pymongo-python3 = %{version}-%{release}
Requires: dnspython
Requires: kerberos
BuildRequires : buildreq-distutils3
BuildRequires : dnspython
BuildRequires : kerberos
Patch1: 0001-Switch-to-kerberos-package-name.patch

%description
PyMongo
        =======

%package license
Summary: license components for the pymongo package.
Group: Default

%description license
license components for the pymongo package.


%package python
Summary: python components for the pymongo package.
Group: Default
Requires: pymongo-python3 = %{version}-%{release}

%description python
python components for the pymongo package.


%package python3
Summary: python3 components for the pymongo package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pymongo package.


%prep
%setup -q -n pymongo-3.9.0
cd %{_builddir}/pymongo-3.9.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1574205256
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pymongo
cp %{_builddir}/pymongo-3.9.0/LICENSE %{buildroot}/usr/share/package-licenses/pymongo/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pymongo/7df059597099bb7dcf25d2a9aedfaf4465f72d8d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
