#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pymongo
Version  : 3.7.2
Release  : 35
URL      : https://files.pythonhosted.org/packages/0f/3a/b90cfa7e27fa92244925826538fa2cf80fed3cbd20a413fd0c1b9705d820/pymongo-3.7.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/0f/3a/b90cfa7e27fa92244925826538fa2cf80fed3cbd20a413fd0c1b9705d820/pymongo-3.7.2.tar.gz
Summary  : Python driver for MongoDB <http://www.mongodb.org>
Group    : Development/Tools
License  : Apache-2.0
Requires: pymongo-python3
Requires: pymongo-license
Requires: pymongo-python
Requires: dnspython
Requires: ipaddress
Requires: pykerberos
BuildRequires : buildreq-distutils3

%description
PyMongo
        =======

%package license
Summary: license components for the pymongo package.
Group: Default

%description license
license components for the pymongo package.


%package python
Summary: python components for the pymongo package.
Group: Default
Requires: pymongo-python3 = %{version}-%{release}

%description python
python components for the pymongo package.


%package python3
Summary: python3 components for the pymongo package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pymongo package.


%prep
%setup -q -n pymongo-3.7.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1539201589
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/pymongo
cp LICENSE %{buildroot}/usr/share/doc/pymongo/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/doc/pymongo/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
